config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :results do
      put :sort, on: :collection
    end
  end

  get 'live/:id' => 'live#show'
  get 'live/:id/results' => 'live#results'

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :test
  include RailsSortable::Model
  #set_sortable :sort  # Indicate a sort column
  # If you do NOT want timestamps to be updated on sorting, use the following option.
  set_sortable :sort, without_updating_timestamps: true
  #handle the sorting here so i don't need to do it in the controllers
  default_scope { order("sort ASC") }
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/live_controller.rb
class LiveController < ApplicationController
	require 'net/http'
	require 'google_custom_search_api'
	require 'yaml'

	def show
		@test = Test.find(params[:id])

	end

	def results
		@test = Test.find(params[:id])
		#for testing purposes (don't hit the rate limiter on the CSE API)
		#file = File.join(Rails.root, 'config', 'test-serp-data.yml')
		#@serp = YAML.load_file(file)
		@serp = GoogleCustomSearchApi.search(params[:q])
		#logger.debug(@serp)
	end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @test = Test.find(params[:test_id])
    @result = @test.results.create(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to test_path(@test), notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      # byebug
      format.html { redirect_to "/tests/#{params[:test_id]}", notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #AJAX route when sortable is updated
  def sort
    params[:order].each do |key,value|
      #byebug
      Result.find(value[:id]).update_attribute(:sort,value[:position])
    end
    #render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:title, :description, :linkShow, :link, :ad, :test_id)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name, :description, :live)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
    	content_for(:title) { page_title }
  	end
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Usability Test' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/live/results.html.erb
<% title params[:q] + " - Google Search" %>
<header>
    <a href='/live/<%= params[:id] %>/'><%= image_tag("small-google-logo.png", class: "small-google-logo") %>

    <form action="/live/<%= params[:id] %>/results" method="get">
      <!--can't make this work!> <img src="microphone.png" class="microphone"> -->
      <input type="search" name="q" value="<%= params[:q] %>">
      <button class="blue-button">
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </form>

    <div class="right-head">
      <%= image_tag("options-image.png", class: "options-image") %>
      <div class="sign-in-button">
        <a href="#">Sign in</a>
      </div>
    </div>
  </header>

<!-- NAVBAR -->
    <section class="navbar clearfix">
      <nav>
        <ul>
          <li><a class="first-navbar" href="#">All</a></li>
          <li><a href="#">Videos</a></li>
          <li><a href="#">Shopping</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Maps</a></li>
          <li><a href="#">More <i class="fa fa-caret-down" aria-hidden="true"></i></a></li>
          <li><a href="#">Search tools</a></li>
        </ul>
      </nav>
      <div class="settings">
        <a href="#" class="settings-button"><i class="fa fa-cog" aria-hidden="true"></i></a>
      </div>
    </section>

<!--RESULTS-->
  <section class="column">
    <section class="results-wrapper">
      <p class="number-speed-results">About 2,860,000 results (0.24 seconds) </p>

<!-- MANUAL TEST RESULTS -->

	<% @test.results.each do |result| %>
	<div class="result">
		<h3 class="result-title">
			<a href="<%= result.link %>"><%= result.title %></a><br>
		</h3>
		<div>
			<% if result.ad %>
			<span class="ad">Ad</span>
			<% end %>
			<cite class="meta-web-address"><%= result.linkShow %></cite>
			<div class="action-menu-web-address">
          		<a href="#"><i class="fa fa-caret-down" aria-hidden="true"></i></a>
        	</div>
			<div class="meta-description">
				<span class="date-result">26 Jul 2013 - </span><%= result.description %>
			</div>
		</div>
	</div>
	<% end %>


<!-- AUTO CSE RESULTS -->

	<% @serp['items'].each do |item| %>
	<div class="result">
		<h3 class="result-title">
			<a href="<%= item['link'] %>"><%= item['title'] %></a>
		</h3>
		<div>
			<cite class="meta-web-address"><%= item['displayLink'] %></cite>
			<div class="action-menu-web-address">
          		<a href="<%= item['link'] %>"><i class="fa fa-caret-down" aria-hidden="true"></i></a>
        	</div>
        	<div class="meta-description">
				<span class="date-result">26 Jul 2013 - </span><%= item['snippet'] %>
			</div>
        </div>
	</div>
	<% end %>
</section>


<!-- RELATED SEARCHES -->
    <section class="related-searches">
      <h3 class="related-searches-title">
        Searches related to <%= params[:q] %>
      </h3>
      <div class="search-column left-col">
        <ul class="rel-search-list">
          <li><a href="#">how to build a web page</a></li>
          <li><a href="#">build web page free</a></li>
          <li><a href="#">jennifer dewalt github</a></li>
          <li><a href="#">yumhacker</a></li>
        </ul>
      </div>
      <div class="search-column right-col">
        <ul class="rel-search-list">
          <li><a href="#">jennifer dewalt linkedin</a></li>
          <li><a href="#">100 days of code challenge</a></li>
          <li><a href="#">180 news website</a></li>
          <li><a href="#">180 websites in 180 days challenge</a></li>
        </ul>
      </div>
    </section>

<!-- PAGES -->
    <section class='pages'>
      <div class="google-o-div">
      	<%= image_tag("Google-o.png") %>
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
      </div>
      <div>
        <ol class="page-numbers">
          <li class="list-reset"><a href="#" class="reset-a">1</a></li>
          <li class="list-reset"><a href="#" class="reset-a">2</a></li>
          <li class="list-reset"><a href="#" class="reset-a">3</a></li>
          <li class="list-reset"><a href="#" class="reset-a">4</a></li>
          <li class="list-reset"><a href="#" class="reset-a">5</a></li>
          <li class="list-reset"><a href="#" class="reset-a">6</a></li>
          <li class="list-reset"><a href="#" class="reset-a">7</a></li>
          <li class="list-reset"><a href="#" class="reset-a">8</a></li>
          <li class="list-reset"><a href="#" class="reset-a">9</a></li>
          <li class="list-reset"><a href="#" class="reset-a">10</a></li>
          <li class="list-reset next"><a href="#" class="reset-a">Next</a></li>
        </ol>

      </div>

    </section>
</section>

<!-- footer -->
    <footer>
      <div class="footer-wrapper">
        <div class="column">
          <div class="location">
            <span class="dot"></span>
            San Francisco - From your Internet address -
            <a href="#" class="reset-a">Use precise location</a>
            -
            <a href="#" class="reset-a">Learn more</a>
          </div>
          <div class="footer-navbar">
            <ul class="list-reset">
              <li class="list-reset"><a href="#" class="reset-a">Help</a></li>
              <li class="list-reset"><a href="#" class="reset-a">Send feedback</a></li>
              <li class="list-reset"><a href="#" class="reset-a">Privacy</a></li>
              <li class="list-reset"><a href="#" class="reset-a">Terms</a></li>
              <li class="list-reset"><a href="#" class="reset-a">Use Google.com</a></li>
            </ul>

          </div>
        </div>
      </div>


    </footer>

app/views/live/show.html.erb
<% title "Google Search" %>
<div class="show-head">
	<div class="right-head">
      <%= image_tag("options-image.png", class: "options-image") %>
      <div class="sign-in-button">
        <a href="#">Sign in</a>
      </div>
    </div>
</div>

<!--MAIN LOGO AND SEARCH-->
<div class="show-search">
	<%= image_tag("googlelogo.png", class: "show-image") %>
	<form action="./results" method="GET">
		<div class="search-box">
			<input type="search" name="q">
			<%= image_tag("google-mic.png") %>
		</div>
		<div class="search-buttons">
			<input type="submit" name="submit" value="Google Search">
			<input type="button" name="lucky" value="I'm Feeling Lucky">
		</div>
	</form>
</div>

<!--FOOTER-->
<div class="search-footer">
	<ul style="float: left;">
		<li>Advertising</li>
		<li>Business</li>
	</ul>
	<ul style="float: right;">
		<li>Privacy</li>
		<li>Terms</li>
		<li>Settings</li>
	</ul>
</div>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :linkShow %><br>
    <%= f.text_field :linkShow %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :ad %><br>
    <%= f.check_box :ad %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.text_field :test_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Linkshow</th>
      <th>Link</th>
      <th>Ad</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.title %></td>
        <td><%= result.description %></td>
        <td><%= result.linkShow %></td>
        <td><%= result.link %></td>
        <td><%= result.ad %></td>
        <td><%= result.test %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @result.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @result.description %>
</p>

<p>
  <strong>Linkshow:</strong>
  <%= @result.linkShow %>
</p>

<p>
  <strong>Link:</strong>
  <%= @result.link %>
</p>

<p>
  <strong>Ad:</strong>
  <%= @result.ad %>
</p>

<p>
  <strong>Test:</strong>
  <%= @result.test %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>